import { motion } from "framer-motion";
import { Trophy, FlaskConical, Users, ArrowUpRight } from "lucide-react";

const CERTIFICATE = "https://drive.google.com/file/d/1Ae9R4I9dE6gi2mLHNtED9-T5mcj3tzuu/view?usp=sharing";
const achievements = [
  { title:"Amazon ML Summer School 2025", subtitle:"Selected through a competitive selection process for an intensive machine learning program.", icon:Trophy, href:CERTIFICATE, label:"Certificate" },
  { title:"NSTL-DRDO Research Internship", subtitle:"Applied physics-informed deep learning to a fluid-dynamics problem and evaluated the trained model quantitatively.", icon:FlaskConical, href:"https://drive.google.com/file/d/1hZZ8K73cURH93r3K8PSY_nyo3O5qGusP/view?usp=sharing", label:"Research report" },
  { title:"Mess Committee Lead", subtitle:"Leading the Girls' Hostel Mess Committee at NIT Agartala for the 2026–27 session, coordinating student needs and issue resolution.", icon:Users },
];
const updateGlow=(e:React.MouseEvent<HTMLDivElement>)=>{const el=e.currentTarget,r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;el.style.setProperty("--mouse-x",`${x}px`);el.style.setProperty("--mouse-y",`${y}px`);el.style.setProperty("--rotate-x",`${((y/r.height)-.5)*-4}deg`);el.style.setProperty("--rotate-y",`${((x/r.width)-.5)*4}deg`)};
const resetGlow=(e:React.MouseEvent<HTMLDivElement>)=>{e.currentTarget.style.setProperty("--rotate-x","0deg");e.currentTarget.style.setProperty("--rotate-y","0deg")};
const TestimonialsSection=()=> <section id="testimonials" className="max-w-7xl mx-auto px-6 py-24"><motion.div initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mb-14 text-center"><h2 className="text-3xl md:text-5xl font-bold">Recognition, research & <span className="text-gradient-primary">leadership.</span></h2><p className="text-muted-foreground max-w-2xl mx-auto mt-4">Milestones that show what she has done beyond coursework — competitive selection, technical research and campus leadership.</p></motion.div><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{achievements.map((a,i)=>{const Icon=a.icon;return <motion.div key={a.title} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} transition={{delay:i*.1}} viewport={{once:true}} onMouseMove={updateGlow} onMouseLeave={resetGlow} className="premium-hover-card achievement-card glass-panel p-8 rounded-3xl border border-foreground/10"><div className="achievement-icon w-14 h-14 rounded-2xl bg-primary/10 text-primary flex items-center justify-center mb-6"><Icon className="w-7 h-7"/></div><h3 className="text-xl font-bold mb-2">{a.title}</h3><p className="text-muted-foreground text-sm">{a.subtitle}</p>{a.href&&<a href={a.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-5 text-sm font-bold text-primary hover:underline">{a.label}<ArrowUpRight size={15}/></a>}<div className="achievement-shine"/></motion.div>})}</div></section>;
export default TestimonialsSection;
